### PR TITLE
✨ Add include_rel & update DevelopmentalStage and Tissue

### LINKED ISSUE #37: Include `part_of` relationship for hsapdv
https://www.ebi.ac.uk/ols4/ontologies/hsapdv/classes?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FHsapDv_0000206

Originated reported from: https://github.com/laminlabs/bionty/issues/81

To get `part_of` relationship:
```
ontology = bt.DevelopmentalStage().ontology
term = ontology.get_term("HsapDv:0000247")
ontology.get_relationship("HsapDv:0000247")
part_of = ontology.get_relationship("part_of")
list(term.objects(part_of))
```

However, it returns a flat list without hierarchies.

### LINKED ISSUE #81: all DevelopmentalStage ontology elements point to the same parents
Hello! 

I hope you had a nice weekend, and sorry to come up with yet another question 😅 : 

There seems to be an issue (which I have also seen in some versions of the HsapDV ontology) where all elements of the ontology point to the same parent (the root parent) HsapDv:0000000

However, this is not the case for the version on OLS http://www.ebi.ac.uk/ols4/ontologies/hsapdv/classes?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FHsapDv_0000206.

I guess you should be able to get the corrected version there(?)

Best,

### PR DESCRIPTION
**Pull request by Zethson**
Fixes https://github.com/laminlabs/bionty/issues/37
Fixes https://github.com/laminlabs/bionty/issues/81

* Adds a new `include_rel` parameter which allows for additional relationships to be specified that are also added to parents. In particular, we are interested in `part_of`.
* Uses `part_of` for DevelopmentalStage and Tissue
* Adds new versions for DevelopmentalStage human and mouse (2024-08-07)
* Adds a new version for Tissue (2024-08-07)

### CODE REVIEW

**Comment by jkobject** [comment]
Hi, sorry to reopen this thread but I was using this new dataset and I can see the parental relationships when doing e.g. `bt.DevelopmentalStage.public().df().loc["HsapDv:0000144"].parents` 

However, I have to add them to my own ontology version (because I need to add some additional elements. to do this I do:
```
names = (
    bt.DevelopmentalStage.public().df().index if not dev_stages else dev_stages
)
records = bt.DevelopmentalStage.from_values(names, field="ontology_id")
ln.save(records)
```
However when I then look at my version I don't see any parental relationships
Screenshot 2024-09-09 at 15 31 27

Is there anything else I should do?

**Comment by sunnyosun** [comment]
Could you try running `bt.DevelopmentalStage.import_from_source()`?

**Comment by jkobject** [comment]
I did but nothing happened or seems to have changed...

**Comment by sunnyosun** [comment]
Sorry, could you specify bt.DevelopmentalStage.import_from_source(update=True)?

**Comment by jkobject** [comment]
seems to be the same... should I remove the initially saved records?

**Comment by sunnyosun** [comment]
Yes, sorry, I'll debug the update parameter.

You can delete the all saved records and re-import, that will certainly have the parents:
```
bt.DevelopmentalStage.filter().delete()
bt.DevelopmentalStage.import_from_source()
```

**Comment by jkobject** [comment]
I got the error 
```
ProtectedError: ("Cannot delete some instances of model 'DevelopmentalStage' because they are referenced through protected foreign keys: 'ArtifactDevelopmentalStage.developmentalstage'.", 
```

**Comment by sunnyosun** [comment]
You have artifacts that are linked to the DevelopmentalStage, would you like to keep them?

**Comment by sunnyosun** [comment]
@jkobject I fixed the bug in `lamindb==0.76.6`, running `bt.DevelopmentalStage.import_from_source()` should also update the parents of existing records.

Please make sure to run update `lamindb[bionty]` to install the latest bionty.

**Comment by jkobject** [comment]
no I can remove the artifacts. I just don't know how to do it, I guess there is an option in the .delete()

Update: Actually I am not sure what that means. Does it mean h5ad files? I don't see why they are linked but I would like to keep the files if possible.

**Comment by jkobject** [comment]
I made the update and run import_from_source(). again nothing has changed. but again I might have to delete the elements first

**Comment by sunnyosun** [comment]
You can try to delete the links via: `bt.DevelopmentalStage.artifacts.through.objects.all().delete()`, then `bt.DevelopmentalStage.filter().delete()` should work

**Comment by jkobject** [comment]
Actually I tried to reload them using `ln.save(bt.DevelopmentalStage.from_values(bt.DevelopmentalStage.public().df().index, field="ontology_id"))` and there it worked

**Comment by jkobject** [comment]
I tried to do the same thing for tissue but it looks as though the update is incomplete:

Screenshot 2024-09-10 at 10 03 08

for devstages at some point the .from_values was returning the right information but not the .filter() and my update (see message above) solved it. Now here both return incomplete information but the .public() has the right one. 

I did bt.Tissue.import_from_source()  already

**Comment by jkobject** [comment]
Now I realize I see the same thing for most bionty ontologies (diseases, cell types etc...) .public() has more parents than what I see on my version when doing bt.[onto].filter(). I update my versions of the ontology by doing `ln.save(bt.[onto].from_values(bt.[onto].public().df().index, field="ontology_id"))`

**Comment by jkobject** [comment]
Hello, any updates on this?

**Comment by sunnyosun** [comment]
> You can try to delete the links via: `bt.DevelopmentalStage.artifacts.through.objects.all().delete()`, then `bt.DevelopmentalStage.filter().delete()` should work

Have you tried this? Sorry I thought you said from_values already solved the problem.

**Comment by jkobject** [comment]
Hi, I am trying it now and it seems to be working! Sorry I got confused with trying too many things.

**Comment by jkobject** [comment]
Hello, sorry I am reopenning this, but I checked MmusDV, and the relationships were not created. It seems just that it was missed as an ontology and I believe just applying the same relationships as in HsapDV should do the trick as it is all properly listed in OLS:
Screenshot 2024-12-05 at 14 17 07

**Pull request merged**
