### PR TITLE
✨ Add compound model

### PR DESCRIPTION
**Pull request by Zethson**
We need a `Compound` model for perturbations where we model Compounds. We decided not to use the name `Drug` but the more generic `Compound` instead. This does not overlap with a potential future `Chemistry` model.

### CODE REVIEW

**Comment by sunnyosun** [comment]
Is there still a reason we want the `Compound` here instead of in the `wetlab`? It won't work yet because it's called `Drug` in bionty.base.

I'll be working on enabling plugin sources for entities with different names, so I think this can then be a model in the wetlab.

**Comment by sunnyosun** [comment]
The problem is also that "Compound" is not a biological entity, it will be confusing to be a model in bionty.

I know we have the same problem for `bionty.base`, but that's no longer user-facing so maybe less of a problem. We can also consider moving the public source yaml outside of bionty.base to include non-bio entities.

**Comment by sunnyosun** [comment]
For now, I'd suggest we focus on compounds in `wetlab` since it will be subject to changes and many more discussions. Doing it here will affect many more instances.

**Comment by Zethson** [comment]
I was already wondering how it works with the different naming.

The other ontologies that wetlab uses such as Gene, EFO, and more are also in Bionty and not wetlab.

> The problem is also that "Compound" is not a biological entity, it will be confusing to be a model in bionty.

Hmm true, the scope of Bionty says that we model biological entities. 

> For now, I'd suggest we focus on compounds in wetlab since it will be subject to changes and many more discussions. Doing it here will affect many more instances.

OK!

**Pull request closed without merging**
