### PR TITLE
✨Add support for local source files

### PR DESCRIPTION
**Pull request by mossjacob**
This is a very small PR and I'm definitely open to better ways of doing this!

Some use-cases, e.g. debugging, may require local files to be loaded as a source.

As an example, I added to `sources_local.yaml` the following lines:
```
Gene:
  ensembl:
    arabidopsis thaliana:
      release-57:
        url: file:///path/to/local/df_arabidopsis thaliana__ensembl__release-57__Gene.parquet
```

With the change in this PR I can load this local parquet file. There's almost certainly a better way of doing this so please do enlighten me!
Thanks

### CODE REVIEW

**Review by sunnyosun — COMMENTED** [review]
This looks good! Could you add a small test for it?

**Comment by sunnyosun** [comment]
Just letting you know that we are working on a better process than modifying the `sources_local.yaml`, all the files that you curated will be all registered in your lamindb instance and tracked there. We'll update you with the new process once we are there!

**Comment by mossjacob** [comment]
Will add a test probably on Monday! Thanks for letting me know, sounds great.

**Comment by Zethson** [comment]
I'm sorry for abusing this PR to ensure that the CI now runs fine on forked PRs but it does now. So with your test on Monday, we can merge this although this design is going to be succeeded in the future.

Thank you very much!

**Comment by mossjacob** [comment]
Have now added the test! thanks

**Comment by Zethson** [comment]
Thank you so much! I made a few edits myself to save you a bit of time and get this in more quickly. I hope you don't mind. If you'd rather have me review smaller PRs instead of making changing to them, please let me know!

1. I ran `pre-commit`. We are using it on all of our repositories and I'd encourage you to use it for your work and all PRs that you make to our repositories. See https://pre-commit.com/
2. We should not hardcode paths like `/tmp` because they might not be writable on Windows devices or clusters. We are now using `tempfile` to create temporary test files.

**Comment by mossjacob** [comment]
No that's perfect, thanks so much for making those improvements. Completely understood re pre-commit and tempfile!

**Pull request merged**
